#!/usr/bin/env python3
"""Section 3.1.4 as TWO boxes, and the email to the Joint Secretariat.

    python3 build_314_and_js_email.py

TWO THINGS HIS SCREENSHOT CORRECTED

3.1.4 is not one field of 2.000 characters. It is TWO fields, labelled a and
b, 2.000 each - so 4.000 characters, and they ask different questions. The
form's own wording for each:

  a. Demonstrate the synergies and complementarities of your proposal with
     other major strategies and/or initiatives at international, EU, national
     or regional levels, particularly those related to sustainable tourism.

  b. Explain how your proposal builds on the results and outputs developed by
     other projects and initiatives... it is mandatory to identify at least
     one output generated by a project funded under another Interreg
     programme involved in the MMM, different from Interreg NEXT MED.

So (a) is the POLICY frameworks and (b) is the PROJECT outputs. That split is
lucky for us, because the ToR names the frameworks it wants to see in (a) and
our synergies section was missing most of them - the single cheapest scoring
gap left in the proposal. And (b) is already in the platform: the MMM outputs
go in through the "choose an output, describe it, Add" widget below the two
text boxes, which is why the whole table should NOT be pasted into a box.

AND THE CO-FINANCING RATE, WHICH IS WORTH 39.000 EUROS

His screenshot of the Budget page shows "Co-financing 11%" - against Total
eligible costs blank and every other figure 0,00 EUR.

I am NOT changing the budget on that. Two reasons.

First, the platform has not computed anything. An 11 next to four zeros is a
field with a default in it, not a rate applied to a budget. Yesterday I wrote
that the running system beats the documentation, and I stand by it - but only
once the system has actually run. This one has not.

Second, the documentation here is not vague prose. The Guidelines state "EU
co-financing rate 92%" and "Co-financing rate by the partnership 8%" in a
table, and FAQ 3.22 asks the question directly - "Can a project choose a
co-financing rate higher than 8%?" - and answers "No. The rate is fixed at 8%
co-financing and 92% EU contribution." That is a numeric table plus an explicit
denial of the alternative.

But the stake is large enough that it cannot be left as a judgement:

    at  8%   co-financing 104.000 EUR,  EU contribution 1.196.000 EUR
    at 11%   co-financing 143.000 EUR,  EU contribution 1.157.000 EUR

A 39.000 euro difference in what six partners must find themselves, and LCEC's
share moves from 24.000 to 33.000 - for a partner whose co-financing source we
have not yet identified. So it goes in the same email as the country question,
and in the meantime the test is free: enter one partner's budget and see what
the platform computes. If it computes 11% of a real number, we have an answer
without waiting for anyone.
"""
import datetime as dt
import re
import sys
from pathlib import Path

from docx import Document
from docx.shared import Cm, Pt, RGBColor

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _shared import here

from build_wp_blended import DIRECT, P, STAFF

BASE = str(here(__file__))
OUT = f"{BASE}/AMMOS_3.1.4_and_JS_email_2026-10-04.docx"

NAVY = RGBColor(0x1F, 0x38, 0x5E)
GREY = RGBColor(0x5A, 0x6B, 0x7D)
RED = RGBColor(0xB4, 0x55, 0x3C)

FLAT = 0.30
LIMIT = 2000
THIN = 0.75

RANGE = re.compile(r"(?<=\d)\s*[–—]\s*(?=[A-Za-z]?\d)")


def clean(t):
    t = str(t)
    t = RANGE.sub("\x00", t)
    t = re.sub(r"(?<!-)\s*--\s*(?!-)", ", ", t)
    t = re.sub(r"\s*[–—]\s*", ", ", t)
    t = t.replace("\x00", "-")
    return re.sub(r",\s*,", ",", t)


def eur(x):
    return f"{x:,.2f}".translate(str.maketrans({",": ".", ".": ","})) + " €"


# ------------------------------------------------------------------ 3.1.4 a
# The ToR names the frameworks. Six real connections, each saying something
# specific, rather than ten decorative ones - the ToR itself warns that
# "the simple listing of projects or outputs/results is not sufficient".
S314A = [
    "AMMOS sits where Mediterranean tourism policy meets climate adaptation "
    "policy, and its contribution to both is the same one: a method a local "
    "authority can actually apply to the shore it manages.",

    "MEDITERRANEAN STRATEGY FOR SUSTAINABLE DEVELOPMENT. The MSSD treats "
    "coastal zone management and sustainable tourism as linked objectives and "
    "calls for applicable tools to reach local level. AMMOS delivers that "
    "unit of transfer: not a strategy but seven field procedures, adapted "
    "sheet by sheet to three shore types and handed to the authorities that "
    "own the sites.",

    "UNION FOR THE MEDITERRANEAN, 2030 GREENER MED. The Ministerial "
    "Declaration on Environment and Climate Change commits to "
    "ecosystem-based adaptation and shared basin monitoring. Our "
    "cross-typology comparability layer is the precondition for that: it is "
    "what allows a Greek dune system, a Lebanese coastal site and an inland "
    "Turkish water body to be read against one another at all.",

    "PACT FOR THE MEDITERRANEAN, EUROPEAN OCEAN PACT. Both frame coastal "
    "resilience alongside the blue economy, and both rest on data that does "
    "not exist for most of the southern and eastern shore. AMMOS produces it "
    "openly for three territories and leaves the protocol to produce more.",

    "EU STRATEGY FOR SUSTAINABLE TOURISM. The strategy asks destinations to "
    "manage visitor pressure, not only to attract visitors. Our demonstration "
    "work channels visitors rather than excluding them - boardwalks, marked "
    "routes and interpretation that move feet off the vulnerable surface "
    "while the site stays open, which is the only version a "
    "tourism-dependent municipality will adopt.",

    "SMART SPECIALISATION. Each receiving region's S3 names tourism and the "
    "blue or agri-environmental economy among its priorities, and the "
    "stewardship committee at each site puts the regional authority in the "
    "same room as the operators - where an S3 priority becomes a local "
    "decision.",
]

# ------------------------------------------------------------------ 3.1.4 b
S314B = [
    "AMMOS does not invent a method. It transfers one, named in the MMM "
    "common database: MMM_IF02, Guidelines for the Sustainable Management of "
    "Beaches, the first output of AMMIRARE under INTERREG ITALIA-FRANCIA "
    "MARITTIMO 2021-2027 - an MMM programme other than Interreg NEXT MED, "
    "and inside the 2021-2027 period the Terms of Reference prioritise. It "
    "holds seven field method sheets, in Italian only.",

    "WHY IT IS NEEDED. The receiving territories have the problem it solves "
    "and no instrument their site managers can apply: it exists only in "
    "Italian and only for western Mediterranean marine shores. HOW IT IS "
    "ADAPTED. Sheet by sheet against three shore types, producing 21 recorded "
    "decisions rather than one claim of transfer. Four of the seven do not "
    "transfer unchanged to an artificial freshwater pond and are substituted "
    "with a drafted equivalent or declared not applicable. "
    "Establishing where a method stops working is what makes it "
    "usable by a fourth territory never in the partnership.",

    "HOW IT IS IMPLEMENTED. WP3 decides and translates into Greek, Turkish "
    "and Arabic, then tests the method by building three baselines with it; "
    "WP4 demonstrates it at all three sites; WP6 carries it into adopted "
    "local plans.",

    "ACCESS AND FURTHER DEVELOPMENT. The source is public, and "
    "CNR - an AMMIRARE partner whose researcher is its first named author - "
    "is a partner here, leading adaptation of the topographic and forcings "
    "sheets. The adapted method, the 21 decisions and the comparability layer "
    "return to the MMM database under open licence, each stating the actions "
    "an adopting organisation must take.",

    "MMM_IF01, Beach Custodians, from the same project, is the engagement "
    "instrument, rewritten for a lake shore and a dune. "
    "Outputs from COMMON, MEDUSA and CROSSDEV (ENI CBC MED) are capitalised "
    "alongside: the beach litter protocol adopted as published, the training "
    "design behind ours, the BEach CLEAN decalogue "
    "already in Arabic, and the Lebanese national contribution our partner "
    "extends.",
]

JS_EMAIL = """Subject: AMMOS - two questions on the Call for Capitalisation Projects \
(partnership country minimum, and the co-financing rate in the e-form)

Dear Joint Secretariat,

We are preparing an application to the Call for Capitalisation Projects under \
Interreg NEXT MED, led by the Hellenic Centre for Marine Research. Two points \
in the call documentation appear to give different answers, and both affect \
decisions we must take before the deadline. We would be grateful for a short \
confirmation on each.

1. MINIMUM NUMBER OF COUNTRIES IN THE PARTNERSHIP

Our partnership comprises six organisations from four countries - Greece (2), \
Turkiye (2), Italy (1) and Lebanon (1) - with at least one EU Mediterranean \
Country and at least one Mediterranean Partner Country.

Section 4.4.2 of the Guidelines for Applicants states that the partnership \
shall represent a minimum of three (3) eligible countries, and error code 007 \
in the e-form User Guide gives an expected value of 3 for the minimum number \
of countries in the partnership.

However, page 37 of the same e-form User Guide, in the Partnership section, \
states that "the minimum number of Countries to be represented is 5".

Could you confirm that the applicable requirement is a minimum of three \
countries, and that a partnership of four countries is therefore admissible?

2. CO-FINANCING RATE SHOWN IN THE E-FORM

The Guidelines state an EU co-financing rate of 92% and a co-financing rate by \
the partnership of 8%, and the FAQ confirms that the rate is fixed at 8% \
co-financing and 92% EU contribution.

In the e-form Budget section, the Co-financing field currently displays 11%, \
with the eligible cost and contribution fields still at zero.

Could you confirm which rate will be applied to the submitted budget? The \
difference between 8% and 11% is approximately 39.000 EUR of own contribution \
across our partnership, and each partner must identify the source of its share \
in the Co-financing and Source of Funding section, so we would prefer to \
inform them of the correct figure once rather than twice.

Thank you very much for your assistance.

With best regards,

Miltiades Kalamaras
on behalf of the Hellenic Centre for Marine Research
Applicant, AMMOS
"""


class Doc:
    def __init__(self):
        self.d = Document()
        s = self.d.sections[0]
        s.left_margin = s.right_margin = Cm(2.0)
        n = self.d.styles["Normal"]
        n.font.name, n.font.size = "Calibri", Pt(10.5)

    def h(self, t, size=13, colour=NAVY, space=12):
        p = self.d.add_paragraph()
        p.paragraph_format.space_before = Pt(space)
        p.paragraph_format.space_after = Pt(4)
        r = p.add_run(clean(t))
        r.bold, r.font.size, r.font.color.rgb = True, Pt(size), colour

    def p(self, t, size=10.5, colour=None, italic=False, bold=False,
          mono=False):
        par = self.d.add_paragraph()
        par.paragraph_format.space_after = Pt(5)
        r = par.add_run(t if mono else clean(t))
        r.font.size, r.italic, r.bold = Pt(size), italic, bold
        if mono:
            r.font.name = "Consolas"
        if colour:
            r.font.color.rgb = colour

    def table(self, head, rows, widths=None):
        t = self.d.add_table(rows=1, cols=len(head))
        t.style = "Table Grid"
        for i, x in enumerate(head):
            c = t.rows[0].cells[i]
            c.text = ""
            r = c.paragraphs[0].add_run(clean(x))
            r.bold, r.font.size, r.font.color.rgb = True, Pt(8.5), NAVY
        for row in rows:
            cells = t.add_row().cells
            for i, v in enumerate(row):
                cells[i].text = ""
                r = cells[i].paragraphs[0].add_run(clean(v))
                r.font.size = Pt(8.5)
                if "[" in str(v) and "]" in str(v):
                    r.font.color.rgb = RED
        if widths:
            for row in t.rows:
                for i, w in enumerate(widths):
                    row.cells[i].width = Cm(w)
        return t


def fit(num, parts):
    """Join, check it fits the box, and refuse to ship if it does not."""
    full = clean("\n\n".join(parts))
    n = len(full)
    assert n <= LIMIT, (
        f"{num} is {n} characters and the box holds {LIMIT}. The platform "
        f"truncates silently on paste, so this does not get sent.")
    flag = "" if n >= LIMIT * THIN else "   <- thin for a scored box"
    print(f"  {num}:  {n} / {LIMIT}   {100 * n / LIMIT:3.0f}%{flag}")
    return full, n


def main():
    elig = {k: DIRECT[k] + STAFF[k] * FLAT for k in DIRECT}
    tot = sum(elig.values())

    a_text, a_n = fit("3.1.4 a", S314A)
    b_text, b_n = fit("3.1.4 b", S314B)

    # The mandatory identification must be in box b, naming a non-NEXT MED
    # MMM programme. If that sentence is missing the box fails a mandatory
    # requirement however well it reads.
    assert "MMM_IF02" in b_text and "ITALIA-FRANCIA MARITTIMO" in b_text, (
        "box b must name the MMM output code and the programme that funded "
        "it - that identification is mandatory")
    assert "2021-2027" in b_text, (
        "box b should say the output is in the period the ToR prioritises")
    for forbidden in (r"\bRAS\b", r"Regione Autonoma", r"Hakanson"):
        assert not re.search(forbidden, a_text + b_text + JS_EMAIL), forbidden
    # The email must not state a rate as settled when that is the question.
    assert "11%" in JS_EMAIL and "8%" in JS_EMAIL, (
        "the email has to put both rates in front of them")

    D = Doc()
    D.h("AMMOS — section 3.1.4 (two boxes) and the email to the Joint "
        "Secretariat", size=16)
    D.p(f"Generated {dt.date.today():%d/%m/%Y}. Your screenshot corrected me: "
        f"3.1.4 is TWO fields of 2.000 characters, a and b, and they ask "
        f"different questions. Both are written to fill their box.",
        size=9.5, colour=GREY, italic=True)

    D.h("3.1.4 a — synergies with strategies and initiatives", size=13)
    D.p(f"{a_n} of {LIMIT} characters. Paste into box a.", size=9,
        colour=GREY, italic=True)
    D.p(a_text)

    D.h("3.1.4 b — how the proposal builds on other projects' outputs",
        size=13)
    D.p(f"{b_n} of {LIMIT} characters. Paste into box b. The MMM outputs "
        f"themselves go in through the widget BELOW the two boxes — choose an "
        f"output, describe it, click Add, one at a time. Do not paste the "
        f"table into a text box; you have already done this part correctly, "
        f"your export shows all five rows in place.", size=9, colour=GREY,
        italic=True)
    D.p(b_text)

    D.h("The email to the Joint Secretariat", size=14)
    D.p("Two questions, one email, and both of them are the kind where being "
        "wrong is expensive and asking is free. Questions close on 14 "
        "October. Copy from here down.", size=10)
    for line in JS_EMAIL.split("\n"):
        D.p(line if line.strip() else " ", size=10, mono=True)

    D.h("What the co-financing rate is worth, so you can see the stake",
        size=13)
    D.table(["", "At 8% (Guidelines and FAQ 3.22)", "At 11% (e-form display)"],
            [["Total eligible cost", eur(tot), eur(tot)],
             ["EU contribution", eur(tot * 0.92), eur(tot * 0.89)],
             ["Partner co-financing", eur(tot * 0.08), eur(tot * 0.11)],
             ["Difference to find", "—", eur(tot * 0.03)]],
            widths=[5.0, 5.6, 5.6])
    D.p("")
    D.p("Per partner, so you know what you would be telling each of them:",
        size=10)
    D.table(["Partner", "Eligible cost", "8% share", "11% share"],
            [[P[k][0], eur(elig[k]), eur(elig[k] * 0.08),
              eur(elig[k] * 0.11)]
             for k in sorted(elig, key=lambda x: -elig[x])],
            widths=[6.0, 3.4, 3.4, 3.4])
    D.p("")
    D.p("I am not changing the budget on the strength of that 11. Your "
        "screenshot shows it next to four zeros — the platform has not "
        "computed anything yet, so that is a default sitting in a field, not "
        "a rate applied to a budget. Yesterday I told you the running system "
        "beats the documentation and I still think so, but only once the "
        "system has actually run.", size=10)
    D.p("And the free test, which beats waiting for anyone: enter one "
        "partner's budget and look at what it computes. If Co-financing "
        "comes out as 8% of a real number, the 11 was a default. If it comes "
        "out as 11%, we have our answer today and the email becomes urgent "
        "rather than precautionary.", size=10, bold=True)

    D.d.save(OUT)
    print(f"\nwrote {OUT}")
    print(f"co-financing at  8%: {eur(tot * 0.08)}   EU {eur(tot * 0.92)}")
    print(f"co-financing at 11%: {eur(tot * 0.11)}   EU {eur(tot * 0.89)}")
    print(f"difference to find : {eur(tot * 0.03)}")


if __name__ == "__main__":
    main()
