#!/usr/bin/env python3
"""The OUTPUTS layer - the piece the form needs and our work package document
never had.

    python3 build_outputs.py

WHY THIS EXISTS

The exported application form numbers everything three levels deep:

    WORK PACKAGE  ->  OUTPUT  ->  ACTIVITY        Activity {WP}.{O}.{A}

and every OUTPUT carries four things our document did not define:

    {WPX_O_Title}  {WPX_O_TargetValue} {WPX_O_TargetUnit}
    {WPX_O_Semester}  {WPX_O_Budget}

A target value, a UNIT, a semester of delivery and a budget. Until these exist
the implementation section cannot be filled at all, and award criterion 2.4
(indicators, 4 points) is scored on exactly this table.

WHAT THE FORM TEMPLATE SETTLES THAT I HAD WRONG OR DID NOT KNOW

1.  MANDATORY WORK PACKAGES HAVE NO OUTPUTS AND NO ACTIVITIES.

    The WP1 and WP2 templates in the form (tables 54 and 55) contain the
    coordinator, the involved partners and one description box. They do NOT
    contain Output rows, Activity rows, Target groups or Target group
    involvement. Only the technical template (table 56) has those.

    So there are EIGHT outputs, not ten: two each in WP3, WP4, WP5, WP6. What
    our document called activities 1.1 to 1.3 and 2.1 to 2.3 are not numbered
    items in the submission - they are prose inside one box each. They still
    get written, they just stop being numbered.

2.  WP2's TITLE IS "Communication and dissemination", not "Communication", and
    the coordinator of both WP1 and WP2 is pre-set to "Applicant". HCMR cannot
    delegate either. Ours already matched; now it is confirmed rather than
    assumed.

3.  EACH OUTPUT HAS ITS OWN BUDGET LINE, and they must sum to the work package
    budget, which must sum to total DIRECT cost (form section 4.2). That is
    asserted below, to the cent, rather than hoped for.

4.  THE OUTPUTS OVERVIEW TABLE HAS FOUR SEMESTER COLUMNS. 24 months, four
    semesters, so a semester is six months and "semester of delivery" is
    ceil(month / 6) of the month the output is finished - not of the month its
    work starts. An output delivered in M22 is semester IV.

WHAT I HAVE NOT INVENTED

Not one RCO or RCR indicator code. Those are defined in the PERFORMANCE
FRAMEWORK METHODOLOGY PAPER, which we still do not have. Every indicator cell
below says so. Target VALUES are ours and defensible; indicator CODES must be
copied from that document.
"""
import datetime as dt
import math
import re
import sys
from pathlib import Path

from docx import Document
from docx.enum.text import WD_BREAK
from docx.shared import Cm, Pt, RGBColor

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from _shared import here

from build_wp_blended import DIRECT, P, STAFF, WPS, matrix

BASE = str(here(__file__))
OUT = f"{BASE}/AMMOS_outputs_and_activities_2026-10-02.docx"

NAVY = RGBColor(0x1F, 0x38, 0x5E)
GREY = RGBColor(0x5A, 0x6B, 0x7D)
RED = RGBColor(0xB4, 0x55, 0x3C)

MONTHS = 24
SEM_LEN = 6
TECHNICAL = ("WP3", "WP4", "WP5", "WP6")
MANDATORY = ("WP1", "WP2")

# The MMM identification is MANDATORY and it has a trap in it. The form:
#   "it is mandatory to identify for reuse and transfer at least one output
#    generated by a project funded under another Interreg programme involved
#    in the MMM, DIFFERENT FROM Interreg NEXT MED"
# AMMIRARE is Interreg Italia-Francia Marittimo 2021-2027 - its own report says
# so - so MMM_IF02 and MMM_IF01 satisfy it. COMMON, MEDUSA and CROSSDEV are ENI
# CBC MED and sit in the database under NX codes; FAQ 5.11 says their results
# may be capitalised "provided at least one output from another MMM Interreg
# Programme is capitalized". They are the second block of the table, never the
# mandatory identification.
MANDATORY_MMM_PREFIX = "MMM_IF"


def eur(x):
    """Form convention: 1.300.000,00 EUR"""
    return f"{x:,.2f}".translate(str.maketrans({",": ".", ".": ","})) + " €"


def sem(month):
    """Semester of delivery from the month the output is FINISHED."""
    assert 1 <= month <= MONTHS, f"month {month} is outside M1-M{MONTHS}"
    return math.ceil(month / SEM_LEN)


ROMAN = {1: "I", 2: "II", 3: "III", 4: "IV"}

RANGE = re.compile(r"(?<=\d)\s*[–—]\s*(?=[A-Za-z]?\d)")


def clean(t):
    t = str(t)
    t = RANGE.sub("\x00", t)
    t = re.sub(r"(?<!-)\s*--\s*(?!-)", ", ", t)
    t = re.sub(r"\s*[–—]\s*", ", ", t)
    t = t.replace("\x00", "-")
    return re.sub(r",\s*,", ",", t)


# ---------------------------------------------------------------- the outputs
# (wp, output index, title, target value, target unit, finish month,
#  share of the WP budget, description, [(activity title, m_from, m_to,
#  lead, description)])
OUTPUTS = [
    # ---------------------------------------------------------------- WP3
    ("WP3", 1,
     "Modular transferability decision: the method assessed sheet by sheet "
     "against each receiving shore type",
     21, "decisions recorded (7 method sheets x 3 sites)", 8, 0.42,
     "The source method is not one instrument but seven method sheets, and the "
     "three receiving sites are a marine dune system, a marine coastal site "
     "and an artificial freshwater pond. Transfer is therefore 21 separate "
     "decisions, not one. This output records every one of them as APPLIED, "
     "SUBSTITUTED or NOT APPLICABLE, with the reason. Establishing where a "
     "method stops working is what makes it usable by a fourth site that was "
     "never in the partnership, and it is the difference between capitalising "
     "an output and restating it.",
     [("Transfer workshop and transfer requirements", 1, 4, "HCMR",
       "The AMMIRARE outputs MMM_IF02 and MMM_IF01 and the COMMON protocols "
       "are presented to the whole partnership by the organisations that "
       "produced them, in English, with the seven method sheets taken one at a "
       "time. Each receiving partner states what their site can and cannot "
       "support. CNR leads on sheets 2.3, 2.4 and 2.6."),
      ("Sheet-by-sheet decision and the adapted method text", 3, 8, "HCMR",
       "Each of the 21 cells is decided and written up with its reason, and "
       "the substituted procedures are drafted: a freshwater littoral "
       "vegetation protocol in place of dune vegetation, a lake-regime "
       "forcings protocol in place of meteo-marine forcings, and an ecological "
       "status indicator recomposed for a system with neither dune nor "
       "banquette. Translated into Greek, Turkish and Arabic, because the "
       "source is 68 pages of Italian and no site manager will use it "
       "otherwise.")]),

    ("WP3", 2,
     "Territorial, biodiversity and tourism baseline for the three "
     "demonstration sites",
     3, "site baselines (one per demonstration site)", 12, 0.58,
     "One comparable baseline per site, built with the adapted method so that "
     "the method is tested by producing it. Shore state and topography, "
     "utilities and access, sea level rise scenarios from 0.2 m to 1 m, "
     "biodiversity state, and the tourism and valuation layer: visitor numbers "
     "and seasonality, a visitor survey covering willingness to visit and "
     "willingness to pay, and the economic value of the shore to the local "
     "economy. Without the tourism layer the baseline measures a habitat; with "
     "it, it measures the asset the municipality is deciding about.",
     [("Physical and biodiversity baselines", 5, 12, "CNR",
       "Emerged and submerged topography and the forcings regime at all three "
       "sites, from method sheets 2.3, 2.4 and 2.6, with drone survey where "
       "the site allows it; GIS mapping of shore state, utilities and roads; "
       "biodiversity state and the ecological status indicator. CNR leads the "
       "physical characterisation and adapts it per site; HCMR carries the "
       "biological sheets. Lebanon is covered as a structured remote review "
       "with local data collection, which is stated plainly rather than "
       "presented as a field mission."),
      ("Tourism and valuation baseline", 5, 12, "UAEG",
       "Visitor counts and seasonality per site per season, the visitor "
       "survey, and the shore's economic contribution to each local economy. "
       "Target group sizes for the communication work package come out of this "
       "activity, which is why it runs early.")]),

    # ---------------------------------------------------------------- WP4
    ("WP4", 1,
     "Three demonstrated shore management installations, one per site",
     3, "sites with the method demonstrated on the ground", 20, 0.66,
     "The method applied, not described: visitor channelling and shore "
     "protection designed from each site's own baseline. Boundary marking, "
     "interpretation signs showing what is protected and why, demountable "
     "modular boardwalks over the vulnerable surface, and demarcated zones "
     "where trampling is degrading vegetation or banks. Demountable matters "
     "for two reasons: it keeps the intervention reversible on an Annex I "
     "habitat, and it keeps the environmental screening proportionate.",
     [("Site designs and consents", 8, 13, "UAEG",
       "Each site's installation designed against its own baseline and its own "
       "consent regime, including the screening outcome for works on or "
       "adjacent to a protected habitat. Designs are signed off by the "
       "authority that will own the installation afterwards, not only by the "
       "partner installing it."),
      ("Installation and first season of operation", 12, 20, "ACIP",
       "Installation at Gomati, Ucari and the Lebanese site, then one full "
       "visitor season observed with the monitoring protocol running, so the "
       "installation is evaluated under load rather than on delivery. No "
       "underwater or bottom cleaning is included at any site.")]),

    ("WP4", 2,
     "Shared cross-typology monitoring platform and common protocol",
     1, "web-GIS platform serving three territories", 18, 0.34,
     "One platform, one protocol, three shore types. The COMMON beach litter "
     "protocol MMM_NX36 is adopted as published so the litter data stays "
     "comparable with the European Environment Agency dataset, and the "
     "adapted method sheets supply the rest. The cross-typology comparability "
     "layer is the genuinely new thing here: it is what allows a freshwater "
     "pond and a marine dune to be read side by side, and it is the output a "
     "future capitalisation call can transfer onward.",
     [("Protocol harmonisation and platform build", 10, 16, "UAEG",
       "The common monitoring protocol assembled from the adapted sheets plus "
       "MMM_NX36 unchanged, and the web-GIS platform built with its own data "
       "collection endpoint so site staff enter observations in the field in "
       "their own language."),
      ("Three monitoring campaigns and the comparability layer", 14, 18,
       "HCMR",
       "The protocol run at all three sites through one cycle, and the "
       "comparability layer written and tested against the three resulting "
       "datasets. Open licensing and data access terms are fixed here, "
       "because the form asks how the project guarantees reuse of what it "
       "produces.")]),

    # ---------------------------------------------------------------- WP5
    ("WP5", 1,
     "Shore Custodians: MMM_IF01 adapted to a lake shore and a coastal dune "
     "and run with schools in three countries",
     9, "school custodian groups (3 per country)", 18, 0.46,
     "AMMIRARE's Beach Custodians transferred to shore types it was not "
     "written for, which is the same adaptation problem as the method sheets "
     "and the same test. Teaching material in Greek, Turkish and Arabic, "
     "delivered with the schools nearest each site so the group survives the "
     "project by being local to it.",
     [("Custodian material adapted and translated", 6, 12, "PIYA",
       "MMM_IF01 rewritten for a lake shore and for a coastal dune, in three "
       "languages, with the field exercises reworked to what each site "
       "actually has. Pi Youth Association leads because youth engagement is "
       "its own field, not a side activity."),
      ("Custodian groups established and running", 10, 18, "PIYA",
       "Three groups per country, each running at least one monitoring round "
       "and one awareness action at its own site, with the group's own data "
       "entering the shared platform.")]),

    ("WP5", 2,
     "Site-manager training and visitor awareness package",
     60, "site managers and local staff trained", 20, 0.54,
     "The people who will still be there in year three. Training built on the "
     "COMMON Capacity Building Training Design Plan MMM_NX38 rather than "
     "designed from scratch, and visitor awareness adapting the BEach CLEAN "
     "decalogue MMM_NX35, which already exists in Arabic. The training is "
     "aimed at municipal and authority staff with a mandate over the site, so "
     "that the management plans in WP6 are written by people who have used the "
     "method.",
     [("Site-manager training programme", 6, 16, "ACIP",
       "The MMM_NX38 design plan adapted to the adapted method and delivered "
       "in each country in the local language, with a practical field module "
       "at the demonstration site itself."),
      ("Visitor awareness at the three sites", 12, 20, "LCEC",
       "The MMM_NX35 decalogue adapted per site and deployed as on-site "
       "material, with the Arabic version extended rather than translated "
       "afresh.")]),

    # ---------------------------------------------------------------- WP6
    ("WP6", 1,
     "Three costed site management plans taken through consultation to "
     "adoption",
     3, "management plans formally adopted by the responsible authority", 22,
     0.55,
     "A plan that is filed changes nothing. Each plan is costed, so the "
     "authority knows what sustaining it requires, and taken through "
     "stakeholder consultation to a formal adoption decision by the body with "
     "the mandate. The Lemnos plan is pursued through the Limnos geopark route "
     "so that maintenance is carried by an existing organisation with its own "
     "activities and income after the project closes, which is the only "
     "durability argument that does not depend on further funding.",
     [("Costed plans and stakeholder consultation", 12, 19, "LCEC",
       "One plan per site, with the protection scheme guidelines and the "
       "maintenance cost, consulted with the operators, authorities and "
       "residents who are affected by it."),
      ("Adoption decisions and the maintenance route", 16, 22, "HCMR",
       "The formal adoption step at each site, and for Lemnos the "
       "negotiation with the Limnos geopark to bring the area into their "
       "network and cover maintenance through their own activities.")]),

    ("WP6", 2,
     "Joint transferability guide and policy recommendations in English and "
     "Arabic",
     1, "transferability guide submitted to the MMM outputs database", 24,
     0.45,
     "What a fourth site needs in order to do this without us: the adapted "
     "method, the 21 transferability decisions and their reasons, the "
     "comparability layer, and the costs. Extends MMM_NX37, which already "
     "consolidates the Lebanese national contribution, and is submitted back "
     "into the MMM outputs database so the next capitalisation call can "
     "transfer it onward. English and Arabic, because the southern shore is "
     "where the method has not yet travelled.",
     [("Transferability guide drafted and reviewed", 18, 23, "HCMR",
       "Written from the project's own record rather than summarised at the "
       "end, including the documented baseline of the Acipayam canyon and "
       "pond as a worked example of a site type the source method never "
       "addressed."),
      ("Policy recommendations and the final conference", 20, 24, "LCEC",
       "Recommendations addressed to the authorities that adopted the plans "
       "and to the programme, presented at the final transferability "
       "conference, and the guide lodged in the MMM database.")]),
]

MMM_MANDATORY = [
    ("MMM_IF02 - Guidelines for the Sustainable Management of Beaches "
     "(published as \"Spiagge che cambiano\"), AMMIRARE, Interreg "
     "Italia-Francia Marittimo 2021-2027",
     "This is the output AMMOS transfers. It is 68 pages in Italian "
     "containing seven method sheets: dune vegetation (2.1), Posidonia "
     "banquettes (2.2), emerged topography (2.3, with drone and BIMM "
     "annexes), submerged topography (2.4), Posidonia meadow (2.5), "
     "meteo-marine forcings (2.6) and ecological status (2.7). WHY IT IS "
     "NEEDED: the receiving territories have the problem the method solves "
     "and no instrument their own site managers can apply - the method exists "
     "only in Italian and only for western Mediterranean marine shores. HOW "
     "IT IS ADAPTED: sheet by sheet against each of three shore types, "
     "producing 21 recorded decisions rather than one claim of transfer; four "
     "of the seven sheets do not transfer unchanged to an artificial "
     "freshwater pond and are either substituted with a drafted equivalent or "
     "declared not applicable with the reason. HOW THE TRANSFER IS "
     "IMPLEMENTED: WP3 output 1 decides and translates; WP3 output 2 tests "
     "the adapted method by producing three baselines with it; WP4 "
     "demonstrates it on the ground. ACCESS AND FURTHER DEVELOPMENT: the "
     "source is a public programme output; CNR, an AMMIRARE partner whose "
     "researcher is the first named author, is a project partner here and "
     "leads the adaptation of sheets 2.3, 2.4 and 2.6. The adapted method, "
     "the 21 decisions and the cross-typology comparability layer are "
     "submitted back to the MMM database under open licence."),
    ("MMM_IF01 - Beach Custodians, AMMIRARE, Interreg Italia-Francia "
     "Marittimo 2021-2027",
     "The engagement instrument that accompanies the method. WHY IT IS "
     "NEEDED: the demonstration installations need a local group that "
     "monitors and maintains them after the project. HOW IT IS ADAPTED: "
     "rewritten for a lake shore and for a coastal dune and translated into "
     "Greek, Turkish and Arabic, with the field exercises reworked to what "
     "each site has. IMPLEMENTED IN: WP5 output 1, nine school custodian "
     "groups across three countries, each feeding the shared platform."),
]

MMM_OTHER = [
    ("COMMON, ENI CBC MED 2014-2020 (database codes MMM_NX35-38)",
     "MMM_NX36 beach litter monitoring guide, adopted as published so the "
     "data stays comparable with the European Environment Agency dataset "
     "(WP4 output 2). MMM_NX38 Capacity Building Training Design Plan, the "
     "basis of the site-manager training (WP5 output 2). MMM_NX35 BEach CLEAN "
     "decalogue, already available in Arabic, adapted for visitor awareness "
     "(WP5 output 2). MMM_NX37, which consolidates the Lebanese national "
     "contribution and which our Lebanese partner extends rather than "
     "restarts (WP6 output 2)."),
    ("MEDUSA, ENI CBC MED 2014-2020 (MMM_NX26, MMM_NX27)",
     "Adventure tourism mapping and hiking e-guides built explicitly to draw "
     "visitors towards alternative areas and reduce pressure on popular ones. "
     "The same visitor-redistribution logic as our channelling work in WP4 "
     "output 1, and the reason our signage directs rather than only "
     "prohibits."),
    ("CROSSDEV, ENI CBC MED 2014-2020 (MMM_NX05, MMM_NX06)",
     "Destination-level local action plans for off-the-beaten-path areas - "
     "the structural model for the costed, adopted management plans in WP6 "
     "output 1."),
]


class Doc:
    def __init__(self):
        self.d = Document()
        s = self.d.sections[0]
        s.left_margin = s.right_margin = Cm(1.6)
        n = self.d.styles["Normal"]
        n.font.name, n.font.size = "Calibri", Pt(10)

    def h(self, t, size=13, colour=NAVY, space=12):
        p = self.d.add_paragraph()
        p.paragraph_format.space_before = Pt(space)
        p.paragraph_format.space_after = Pt(4)
        r = p.add_run(clean(t))
        r.bold, r.font.size, r.font.color.rgb = True, Pt(size), colour

    def p(self, t, size=10, colour=None, italic=False, bold=False):
        par = self.d.add_paragraph()
        par.paragraph_format.space_after = Pt(4)
        r = par.add_run(clean(t))
        r.font.size, r.italic, r.bold = Pt(size), italic, bold
        if colour:
            r.font.color.rgb = colour

    def table(self, head, rows, widths=None):
        t = self.d.add_table(rows=1, cols=len(head))
        t.style = "Table Grid"
        for i, x in enumerate(head):
            c = t.rows[0].cells[i]
            c.text = ""
            r = c.paragraphs[0].add_run(clean(x))
            r.bold, r.font.size, r.font.color.rgb = True, Pt(8.5), NAVY
        for row in rows:
            cells = t.add_row().cells
            for i, v in enumerate(row):
                cells[i].text = ""
                r = cells[i].paragraphs[0].add_run(clean(v))
                r.font.size = Pt(8.5)
                if str(row[0]).startswith("TOTAL"):
                    r.bold = True
                if "[" in str(v) and "]" in str(v):
                    r.font.color.rgb = RED
        if widths:
            for row in t.rows:
                for i, w in enumerate(widths):
                    row.cells[i].width = Cm(w)
        return t

    def page(self):
        self.d.add_paragraph().add_run().add_break(WD_BREAK.PAGE)


# ------------------------------------------------------------------- checks
def check(wp_budget):
    """Everything that must be true before this is pasted into a submission."""
    fails = []

    wp_titles = {w[0]: w[1] for w in WPS}
    wp_months = {w[0]: w[4] for w in WPS}
    wp_lead = {w[0]: w[3] for w in WPS}

    # 1. Only technical work packages carry outputs.
    used = sorted({o[0] for o in OUTPUTS})
    if used != sorted(TECHNICAL):
        fails.append(f"outputs are attached to {used}, expected "
                     f"{sorted(TECHNICAL)} - the form gives WP1 and WP2 no "
                     f"output rows at all")

    # 2. Output indices contiguous from 1 within each work package.
    for wp in TECHNICAL:
        idx = [o[1] for o in OUTPUTS if o[0] == wp]
        if idx != list(range(1, len(idx) + 1)):
            fails.append(f"{wp} output indices are {idx}, must be 1..n")

    # 3. Shares sum to 1 and output budgets sum to the WP budget, to the cent.
    for wp in TECHNICAL:
        rows = [o for o in OUTPUTS if o[0] == wp]
        share = sum(o[6] for o in rows)
        if abs(share - 1.0) > 1e-9:
            fails.append(f"{wp} output shares sum to {share}, not 1.0")
        got = sum(round(wp_budget[wp] * o[6], 2) for o in rows)
        if abs(got - wp_budget[wp]) > 0.02:
            fails.append(f"{wp} output budgets sum to {got:.2f} but the work "
                         f"package holds {wp_budget[wp]:.2f}")

    # 4. Technical WP budgets plus mandatory WP budgets equal total direct.
    tot = sum(wp_budget.values())
    direct = sum(DIRECT.values())
    if abs(tot - direct) > 0.02:
        fails.append(f"work package budgets sum to {tot:.2f}, total direct "
                     f"cost is {direct:.2f}")

    # 5. Every activity sits inside its work package's own month window, and
    #    the output is not delivered before its last activity finishes.
    for wp, oi, title, tv, unit, fin, share, desc, acts in OUTPUTS:
        lo, hi = (int(x) for x in re.findall(r"M(\d+)", wp_months[wp]))
        for ai, (atitle, m0, m1, lead, adesc) in enumerate(acts, 1):
            if not (m0 <= m1):
                fails.append(f"A{wp[2]}.{oi}.{ai} runs M{m0}-M{m1}")
            if m0 < lo or m1 > hi:
                fails.append(f"A{wp[2]}.{oi}.{ai} runs M{m0}-M{m1}, outside "
                             f"{wp} which runs {wp_months[wp]}")
            if lead not in P:
                fails.append(f"A{wp[2]}.{oi}.{ai} is led by {lead!r}, "
                             f"not a partner")
        last = max(a[2] for a in acts)
        if fin < last:
            fails.append(f"Output{wp[2]}.{oi} is delivered M{fin} but its "
                         f"activities run to M{last}")
        if fin > MONTHS:
            fails.append(f"Output{wp[2]}.{oi} delivers M{fin}, past M{MONTHS}")
        if not isinstance(tv, int) or tv <= 0:
            fails.append(f"Output{wp[2]}.{oi} target value is {tv!r}")
        if not unit or unit[0].isupper():
            fails.append(f"Output{wp[2]}.{oi} unit {unit!r} reads like a "
                         f"sentence, the form wants a unit")

    # 6. Every partner leads at least one activity. A partner that leads
    #    nothing is a partner an evaluator will ask about, and a partner who
    #    will not defend the proposal.
    leads = {a[3] for o in OUTPUTS for a in o[8]} | set(
        wp_lead[wp] for wp in wp_lead)
    idle = sorted(set(P) - leads)
    if idle:
        fails.append(f"these partners lead nothing: {idle}")

    # 7. The mandatory MMM identification must be an IF-coded output. An
    #    NX-coded one would be a NEXT MED output and would not satisfy the
    #    requirement - FAQ 5.11.
    if not any(MANDATORY_MMM_PREFIX in c for c, _ in MMM_MANDATORY):
        fails.append("the mandatory MMM identification contains no "
                     f"{MANDATORY_MMM_PREFIX} output - an NX code does not "
                     "satisfy 'different from Interreg NEXT MED'")
    for code, _ in MMM_MANDATORY:
        if "MMM_NX" in code:
            fails.append(f"{code[:24]} is in the MANDATORY block but is "
                         f"NX-coded")

    # 8. Nothing invented where a programme document is the source.
    for code, body in MMM_MANDATORY + MMM_OTHER:
        if re.search(r"\b(RCO|RCR)\s?\d", body):
            fails.append(f"{code[:24]} cites an indicator code - those come "
                         f"from the Performance Framework paper, which we do "
                         f"not have")

    # 9. RAS must not appear anywhere in a partner-facing AMMOS document.
    blob = " ".join(
        [t for o in OUTPUTS for t in (o[2], o[7])]
        + [a[4] for o in OUTPUTS for a in o[8]]
        + [b for _, b in MMM_MANDATORY + MMM_OTHER])
    for forbidden in (r"\bRAS\b", r"Regione Autonoma", r"Hakanson"):
        if re.search(forbidden, blob):
            fails.append(f"the text contains {forbidden!r}, which must not "
                         f"appear in any partner-facing AMMOS document")

    assert not fails, "NOT SHIPPING:\n  - " + "\n  - ".join(fails)
    return True


def main():
    m = matrix()
    wp_budget = {w[0]: sum(m[p].get(w[0], 0.0) for p in m) for w in WPS}
    wp_titles = {w[0]: w[1] for w in WPS}
    wp_lead = {w[0]: w[3] for w in WPS}
    wp_months = {w[0]: w[4] for w in WPS}

    check(wp_budget)

    D = Doc()
    D.h("AMMOS — outputs, target values, semesters and activities",
        size=16)
    D.p(f"Generated {dt.date.today():%d/%m/%Y}. This is the layer the form "
        f"requires and our work package document did not have. Eight outputs "
        f"across the four technical work packages, each with a target value, "
        f"a unit, a semester of delivery and a budget; sixteen activities "
        f"numbered the way the platform numbers them. Every budget figure is "
        f"computed from the agreed partner budget, not typed.",
        size=9.5, colour=GREY, italic=True)

    D.h("Read this before you paste anything", size=12)
    for t in [
        "WP1 and WP2 have NO outputs and NO activities. The form's templates "
        "for the two mandatory work packages contain a coordinator, the "
        "involved partners and one description box — no Output rows, no "
        "Activity rows, no target groups. So our numbered activities 1.1 to "
        "1.3 and 2.1 to 2.3 become prose inside one box each. They still get "
        "written; they stop being numbered.",
        "WP2 is titled \"Communication and dissemination\" and the "
        "coordinator of both WP1 and WP2 is pre-set to Applicant. HCMR "
        "cannot delegate either one.",
        "A semester is six months, and the semester of delivery is of the "
        "month the output is FINISHED, not when its work starts. The outputs "
        "overview table has four columns because the project is 24 months.",
        "Each output carries its own budget line and they must sum to the "
        "work package. That is checked to the cent here, so if the platform "
        "disagrees with a figure below, a partner's budget has changed since "
        "this was generated.",
        "The target VALUES below are ours and defensible. The indicator "
        "CODES are not here at all, because they live in the Performance "
        "Framework Methodology Paper. Nothing is invented in their place.",
    ]:
        D.p("•  " + t, size=9.5)

    # ----------------------------------------------- the mandatory MMM table
    D.page()
    D.h("Section 3.1.4 b — the MMM identification, which is MANDATORY",
        size=14)
    D.p("The form: \"it is mandatory to identify for reuse and transfer at "
        "least one output generated by a project funded under another "
        "Interreg programme involved in the MMM, DIFFERENT FROM Interreg "
        "NEXT MED, and included in the common database of outputs\".",
        size=9.5, italic=True, colour=GREY)
    D.p("This matters more than it looks. AMMIRARE is Interreg "
        "Italia-Francia Marittimo — its own report says so — so "
        "MMM_IF02 and MMM_IF01 satisfy the requirement. COMMON, MEDUSA and "
        "CROSSDEV are ENI CBC MED and sit in the database under NX codes. "
        "FAQ 5.11 allows their results to be capitalised \"provided at least "
        "one output from another MMM Interreg Programme is capitalized\" "
        "— so they belong in the second block, never in the mandatory "
        "identification. Had the proposal been anchored on COMMON, the "
        "mandatory requirement would not have been met.",
        size=10, bold=True)
    D.p("One more thing the FAQ gives us free of charge: involving the "
        "organisation that originally developed the output is \"strongly "
        "encouraged\" (5.12) and the developer may be a partner (5.13). CNR "
        "is an AMMIRARE partner and Dr Simeone is the first named author of "
        "MMM_IF02. That belongs in this box explicitly, because it answers "
        "the access-and-reuse question in the same sentence as the "
        "encouragement.", size=10)
    D.table(["Output code and name",
             "Why it is needed, and how it will be adapted, reused, further "
             "developed and scaled up"],
            [[c, b] for c, b in MMM_MANDATORY], widths=[5.2, 12.4])
    D.p("")
    D.p("Other outputs and initiatives to be exploited (second block of the "
        "same table)", size=10, bold=True)
    D.table(["Name of the project (and Programme under which it was funded)",
             "List of outputs to be exploited"],
            [[c, b] for c, b in MMM_OTHER], widths=[5.2, 12.4])

    # ------------------------------------------------------- outputs summary
    D.page()
    D.h("4.3 Outputs overview per work package", size=14)
    rows = []
    for wp, oi, title, tv, unit, fin, share, desc, acts in OUTPUTS:
        rows.append([f"Output{wp[2]}.{oi}", title,
                     f"{tv}", unit, ROMAN[sem(fin)], f"M{fin}",
                     eur(round(wp_budget[wp] * share, 2))])
    rows.append(["TOTAL", "eight outputs, four technical work packages", "", "",
                 "", "",
                 eur(sum(round(wp_budget[o[0]] * o[6], 2) for o in OUTPUTS))])
    D.table(["Code", "Output title", "Target", "Unit", "Sem.", "Done",
             "Budget"], rows, widths=[1.7, 5.4, 1.1, 3.5, 1.0, 1.0, 2.6])

    D.p("")
    D.p("The same thing laid out the way the platform's semester grid asks "
        "for it — each output in the column of the semester it is "
        "delivered in:", size=9.5, colour=GREY)
    grid = []
    for wp in TECHNICAL:
        cells = {1: [], 2: [], 3: [], 4: []}
        for o in OUTPUTS:
            if o[0] == wp:
                cells[sem(o[5])].append(f"O{wp[2]}.{o[1]}")
        grid.append([f"{wp} {wp_titles[wp]}"]
                    + [", ".join(cells[s]) or "none" for s in (1, 2, 3, 4)])
    D.table(["Outputs overview per work package", "I sem.", "II sem.",
             "III sem.", "IV sem."], grid, widths=[7.0, 2.6, 2.6, 2.6, 2.6])

    D.p("")
    D.p("Read that grid honestly, because an evaluator will. Nothing lands "
        "in semester I, which is right: an output delivered in the first six "
        "months of a transfer project is either trivial or existed before the "
        "project did. But FOUR OF THE EIGHT land in semester IV, and that is "
        "the one structural weakness in this plan. If the project slips three "
        "months, half the outputs slip past the end of it.", size=9.5)
    D.p("It is also largely unavoidable and we should say so rather than hide "
        "it. A management plan cannot be adopted before the demonstration it "
        "is based on, and a transferability guide cannot be written before "
        "there is something to transfer. The sequence is the argument. What we "
        "can do, and what WP1's risk procedure should state explicitly, is "
        "that each semester-IV output has a defined partial state that is "
        "reportable earlier — plans consulted before adopted, guide drafted "
        "before lodged — so a slip costs completeness rather than the whole "
        "output. That sentence belongs in the WP1 monitoring box, where "
        "criterion 4.1 is looking for it.", size=9.5)

    # -------------------------------------------- budget per WP, for 4.2
    D.p("")
    D.h("4.2 Budget per work package", size=12)
    rows = [[wp, wp_titles[wp],
             "mandatory" if wp in MANDATORY else "technical",
             wp_lead[wp], wp_months[wp], eur(wp_budget[wp])]
            for wp in [w[0] for w in WPS]]
    rows.append(["TOTAL", "total budgeted DIRECT cost", "", "", "",
                 eur(sum(wp_budget.values()))])
    D.table(["WP", "Title", "Type", "Coordinator", "Months", "Budget"], rows,
            widths=[1.2, 6.4, 1.8, 2.4, 2.0, 2.8])
    D.p(f"These are DIRECT costs, which is what form section 4.2 asks for. "
        f"Total eligible cost is "
        f"{eur(sum(DIRECT.values()) + sum(STAFF.values()) * 0.30)} once the "
        f"two flat rates are added, and the 50% rule in the Guidelines is "
        f"written on that figure, not on this one. The platform will show you "
        f"the direct-cost percentage. They are different numbers and both are "
        f"correct.", size=9, colour=GREY)

    # ------------------------------------------------- the outputs in detail
    for wp in TECHNICAL:
        D.page()
        D.h(f"{wp} — {wp_titles[wp]}", size=15)
        D.p(f"Coordinator: {wp_lead[wp]}    ·    Runs {wp_months[wp]}"
            f"    ·    Budget {eur(wp_budget[wp])}",
            size=9.5, colour=GREY, bold=True)
        for o in [x for x in OUTPUTS if x[0] == wp]:
            _, oi, title, tv, unit, fin, share, desc, acts = o
            D.h(f"Output{wp[2]}.{oi}  —  {title}", size=11.5, space=10)
            D.table(["Target value", "Unit", "Semester of delivery", "Budget"],
                    [[f"{tv}", unit, f"{ROMAN[sem(fin)]} sem. (by M{fin})",
                      eur(round(wp_budget[wp] * share, 2))]],
                    widths=[2.2, 6.4, 4.2, 4.0])
            D.p("")
            D.p("Output description", size=9, bold=True, colour=GREY)
            D.p(desc, size=9.5)
            for ai, (atitle, m0, m1, lead, adesc) in enumerate(acts, 1):
                D.p(f"Activity {wp[2]}.{oi}.{ai} (A{wp[2]}.{oi}.{ai})  "
                    f"—  {atitle}", size=10, bold=True)
                D.p(f"Implementing period: M{m0} to M{m1}    ·    "
                    f"Leads: {P[lead][0]}", size=9, colour=GREY)
                D.p(adesc, size=9.5)

    # ------------------------------------------------------- what is missing
    D.page()
    D.h("3.2.4 Indicators — and what is still blocking it", size=14)
    D.p("The form wants result indicators and output indicators, each with a "
        "target value and a description. The target values are above and "
        "below. The indicator CODES are defined in the Performance Framework "
        "Methodology Paper, which we do not have, and inventing an RCO or RCR "
        "code is the one error in this section that cannot be corrected after "
        "submission.", size=10)
    D.table(["Project expected result", "Result indicator",
             "Target value", "Description"],
            [["Receiving Mediterranean territories apply a transferred, "
              "adapted shore management method and sustain it through adopted "
              "local plans",
              "[FROM THE PERFORMANCE FRAMEWORK METHODOLOGY PAPER — the "
              "result indicator under SO 2.2]",
              "3",
              "Three sites with the adapted method in use and a costed "
              "management plan formally adopted by the responsible "
              "authority, across three countries and three shore types."]],
            widths=[4.6, 4.2, 1.6, 7.2])
    D.p("")
    D.table(["Project output", "Output indicator", "Target value",
             "Description"],
            [[f"Output{o[0][2]}.{o[1]} — {o[2]}",
              "[FROM THE PERFORMANCE FRAMEWORK METHODOLOGY PAPER]",
              f"{o[3]} {o[4]}",
              o[7][:240] + ("..." if len(o[7]) > 240 else "")]
             for o in OUTPUTS], widths=[4.6, 3.4, 2.4, 7.2])

    D.p("")
    D.h("What I need from you, in the order it blocks things", size=12)
    for n, t in enumerate([
        "The PERFORMANCE FRAMEWORK METHODOLOGY PAPER and the TERMS OF "
        "REFERENCE, from the same programme page as the Guidelines. Twelve "
        "points sit behind those two documents and I cannot write a single "
        "indicator code without the first one.",
        "Your decision on the eight outputs and their target values. I have "
        "committed to numbers — 21 decisions, 3 baselines, 3 "
        "installations, 1 platform, 9 custodian groups, 60 trained staff, 3 "
        "adopted plans, 1 guide — because a blank target value scores "
        "nothing and a number you can argue down is worth more than a gap. "
        "The two I am least sure of are 60 trained staff and 9 custodian "
        "groups; both depend on partners who have not sent numbers.",
        "The visitor and target-group numbers, still outstanding from "
        "Acipayam since September, and LCEC's past coastal work. These close "
        "section 3.1.3, the communication strategy and the tourism baseline "
        "together.",
        "LCEC's source of 8% co-financing, about 24.000 €. The "
        "co-financing table forces each partner to name it.",
        "The North Aegean Periphery associated partner statement. Criterion "
        "3.2 is 4 points and we currently score zero on it, and a signature "
        "is the slowest thing in any consortium.",
        "Environmental screening, checklists A, B and C. It is roughly a "
        "third of the form and untouched. Demountable boardwalks adjacent to "
        "an Annex I habitat will not stop at checklist A, and this is the "
        "item most likely to be underestimated between now and the 29th.",
    ], 1):
        D.p(f"{n}.  {t}", size=9.5)

    D.d.save(OUT)
    print(f"wrote {OUT}")
    print(f"\n{len(OUTPUTS)} outputs, "
          f"{sum(len(o[8]) for o in OUTPUTS)} activities, all checks passed")
    for wp in TECHNICAL:
        rows = [o for o in OUTPUTS if o[0] == wp]
        print(f"  {wp}  {eur(wp_budget[wp]):>16s}  "
              f"-> " + " + ".join(
                  f"O{wp[2]}.{o[1]} {eur(round(wp_budget[wp] * o[6], 2))}"
                  f" sem {ROMAN[sem(o[5])]}" for o in rows))


if __name__ == "__main__":
    main()
